branches:
  except:
    - gh-pages
language: scala
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
script:
  - if [[ $TRAVIS_SCALA_VERSION == '2.11.11' ]]; then sbt ++$TRAVIS_SCALA_VERSION coreNative/compile ; fi
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
