branches:
  except:
    - gh-pages
language: scala
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - if [[ $TRAVIS_SCALA_VERSION == '2.11.11' ]]; then sbt coreNative/test ; fi
