branches:
  except:
    - gh-pages
language: scala
scala:
  - 2.12.8
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
script:
  - sbt validate
after_success:
  - bash <(curl -s https://codecov.io/bash)
